#!/usr/bin/env python3
"""
YouTube OAuth 2.0 Setup Script
One-time setup to obtain a refresh token for YouTube Data API v3.

Usage:
    python3 setup_oauth.py

Prerequisites:
    1. Create a Google Cloud project at https://console.cloud.google.com
    2. Enable "YouTube Data API v3" and "YouTube Analytics API"
    3. Create OAuth 2.0 credentials (Desktop app type)
    4. Add yourself as a test user in the OAuth consent screen
"""

import http.server
import json
import os
import sys
import urllib.parse
import urllib.request
import webbrowser
import threading

SKILL_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
ENV_FILE = os.path.join(SKILL_DIR, ".env")

SCOPES = [
    "https://www.googleapis.com/auth/youtube",
    "https://www.googleapis.com/auth/youtube.force-ssl",
    "https://www.googleapis.com/auth/youtube.upload",
    "https://www.googleapis.com/auth/yt-analytics.readonly",
]

REDIRECT_PORT = 8976
REDIRECT_URI = f"http://localhost:{REDIRECT_PORT}"

auth_code = None
server_done = threading.Event()


class OAuthHandler(http.server.BaseHTTPRequestHandler):
    def do_GET(self):
        global auth_code
        query = urllib.parse.urlparse(self.path).query
        params = urllib.parse.parse_qs(query)

        if "code" in params:
            auth_code = params["code"][0]
            self.send_response(200)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(b"""
                <html><body style="font-family:system-ui;text-align:center;padding:60px;">
                <h1>Authorization successful!</h1>
                <p>You can close this tab and return to the terminal.</p>
                </body></html>
            """)
        else:
            error = params.get("error", ["unknown"])[0]
            self.send_response(400)
            self.send_header("Content-Type", "text/html")
            self.end_headers()
            self.wfile.write(f"""
                <html><body style="font-family:system-ui;text-align:center;padding:60px;">
                <h1>Authorization failed</h1>
                <p>Error: {error}</p>
                </body></html>
            """.encode())

        server_done.set()

    def log_message(self, format, *args):
        pass  # Suppress server logs


def load_existing_env():
    """Load existing .env values if file exists."""
    env = {}
    if os.path.exists(ENV_FILE):
        with open(ENV_FILE) as f:
            for line in f:
                line = line.strip()
                if line and not line.startswith("#") and "=" in line:
                    key, val = line.split("=", 1)
                    env[key.strip()] = val.strip()
    return env


def save_env(env):
    """Save environment variables to .env file."""
    with open(ENV_FILE, "w") as f:
        f.write("# YouTube OAuth Credentials\n")
        f.write("# Generated by setup_oauth.py\n\n")
        for key, val in env.items():
            f.write(f"{key}={val}\n")
    os.chmod(ENV_FILE, 0o600)
    print(f"\nCredentials saved to {ENV_FILE}")


def exchange_code(client_id, client_secret, code):
    """Exchange authorization code for tokens."""
    data = urllib.parse.urlencode({
        "code": code,
        "client_id": client_id,
        "client_secret": client_secret,
        "redirect_uri": REDIRECT_URI,
        "grant_type": "authorization_code",
    }).encode()

    req = urllib.request.Request(
        "https://oauth2.googleapis.com/token",
        data=data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )

    with urllib.request.urlopen(req) as resp:
        return json.loads(resp.read())


def main():
    print("=" * 60)
    print("  YouTube OAuth 2.0 Setup")
    print("=" * 60)
    print()

    existing = load_existing_env()

    client_id = existing.get("YOUTUBE_CLIENT_ID", "")
    client_secret = existing.get("YOUTUBE_CLIENT_SECRET", "")

    if client_id:
        print(f"Existing Client ID found: {client_id[:20]}...")
        reuse = input("Use existing credentials? [Y/n]: ").strip().lower()
        if reuse == "n":
            client_id = ""
            client_secret = ""

    if not client_id:
        print("\nGet credentials from: https://console.cloud.google.com/apis/credentials")
        print("Create an OAuth 2.0 Client ID (type: Desktop app)\n")
        client_id = input("Client ID: ").strip()
        client_secret = input("Client Secret: ").strip()

    if not client_id or not client_secret:
        print("Error: Client ID and Client Secret are required.")
        sys.exit(1)

    # Build OAuth URL
    scope_str = " ".join(SCOPES)
    auth_params = urllib.parse.urlencode({
        "client_id": client_id,
        "redirect_uri": REDIRECT_URI,
        "response_type": "code",
        "scope": scope_str,
        "access_type": "offline",
        "prompt": "consent",
    })
    auth_url = f"https://accounts.google.com/o/oauth2/v2/auth?{auth_params}"

    # Start local server
    server = http.server.HTTPServer(("localhost", REDIRECT_PORT), OAuthHandler)
    server_thread = threading.Thread(target=server.handle_request)
    server_thread.daemon = True
    server_thread.start()

    print(f"\nOpening browser for authorization...")
    print(f"If it doesn't open, visit:\n{auth_url}\n")
    webbrowser.open(auth_url)

    print("Waiting for authorization...")
    server_done.wait(timeout=300)
    server.server_close()

    if not auth_code:
        print("Error: No authorization code received. Timed out or denied.")
        sys.exit(1)

    print("Authorization code received. Exchanging for tokens...")

    try:
        tokens = exchange_code(client_id, client_secret, auth_code)
    except Exception as e:
        print(f"Error exchanging code: {e}")
        sys.exit(1)

    refresh_token = tokens.get("refresh_token")
    if not refresh_token:
        print("Error: No refresh token received. Try revoking access and re-running.")
        print("Revoke at: https://myaccount.google.com/permissions")
        sys.exit(1)

    # Save credentials
    env = {
        "YOUTUBE_CLIENT_ID": client_id,
        "YOUTUBE_CLIENT_SECRET": client_secret,
        "YOUTUBE_REFRESH_TOKEN": refresh_token,
    }
    save_env(env)

    # Verify by getting access token
    print("\nVerifying credentials...")
    verify_data = urllib.parse.urlencode({
        "client_id": client_id,
        "client_secret": client_secret,
        "refresh_token": refresh_token,
        "grant_type": "refresh_token",
    }).encode()

    req = urllib.request.Request(
        "https://oauth2.googleapis.com/token",
        data=verify_data,
        headers={"Content-Type": "application/x-www-form-urlencoded"},
    )

    try:
        with urllib.request.urlopen(req) as resp:
            result = json.loads(resp.read())
            if result.get("access_token"):
                print("Access token obtained successfully!")

                # Get channel info
                ch_req = urllib.request.Request(
                    "https://www.googleapis.com/youtube/v3/channels?part=snippet&mine=true",
                    headers={"Authorization": f"Bearer {result['access_token']}"},
                )
                with urllib.request.urlopen(ch_req) as ch_resp:
                    ch_data = json.loads(ch_resp.read())
                    if ch_data.get("items"):
                        channel = ch_data["items"][0]["snippet"]
                        print(f"\nConnected to channel: {channel['title']}")
    except Exception as e:
        print(f"Warning: Verification failed: {e}")
        print("Credentials were saved. You may need to check your API settings.")

    print("\nSetup complete! You can now use the YouTube uploader skill.")
    print("Test with: /youtube-upload")


if __name__ == "__main__":
    main()
